### ISSUE TITLE
NullPointer Error

### ISSUE THREAD

**Issue by zakariansudosu** [runetopic/openosrs#2]
Hi man, thanks for updating this dead project. I;ve some questions and learning java using this client

How to update this client?

if im updating rsversion, example from rsversion = 209 to rsversion = 210

When building client, always getting error like this

client:inject'.java.lang.NullPointerException

Thanks man

**Comment by tyler27** [comment]
You need to go through a few steps. Most of the steps are located in the gradle task.

Typically a rev upgrade goes like follows:

Download new gamepack.
Deob gamepack
Update the mappings
Deob the updated gamepack and then update the runescape-client module.

It takes a little bit to figure it out, tbf.
